name: Digger Manual Plan

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to run plan for'
        required: true

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write

jobs:
  digger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Digger Plan
        uses: diggerhq/digger@vLatest

