name: Digger Plan

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write
  id-token: write

jobs:
  digger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@vLatest
        with:
          # Setup terraform
          aws-access-key-id: # optional
          # AWS secret access key
          aws-secret-access-key: # optional
          # ARN of AWS IAM role to assume using OIDC
          # AWS region
          aws-role-to-assume: arn:aws:iam::924144197303:oidc-provider/token.actions.githubusercontent.com
          aws-region: us-east-1
          setup-terraform: true
          terraform-version: 1.6.6
          configure-checkout: true
          disable-locking: true
          no-backend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

