name: Digger Plan

# on:
#   pull_request:
#     types: [opened, reopened, synchronize]


on:
  workflow_dispatch:
    inputs:
      spec:
        required: true
      run_name:
        required: false

run-name: '${{inputs.run_name}}'
permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write
  id-token: write

jobs:
  digger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"
      - uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ inputs.spec }}
          aws-role-to-assume: arn:aws:iam::924144197303:role/arziandiggercicd
          aws-region: us-east-1
          setup-terraform: true
          terraform-version: 1.6.6
          # setup-checkov: true
          # configure-checkout: true
          # disable-locking: true
          # no-backend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

