name: Digger Plan

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write

jobs:
  digger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@vLatest
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}