name: Digger Plan

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write

jobs:
  digger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: diggerhq/digger@vLatest
        with:
          # Setup terraform
          setup-terraform: true
          terraform-version: 1.6.6
          configure-checkout: true
          disable-locking: true
          no-backend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

