name: Digger Plan

on:
  pull_request:
    branches: [ "main" ]
    types: [closed, opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write
  issues: read
  statuses: write
  id-token: write

jobs:
  digger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: diggerhq/digger@v0.2.0
        with:
          aws-role-to-assume: arn:aws:iam::924144197303:role/arziandiggercicd
          aws-region: us-east-1
          # setup-terraform: true
          # terraform-version: 1.6.6
          # configure-checkout: true
          # disable-locking: true
          # no-backend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}

